name: party_quest
description: Unleash your imagination.

dependencies:
  share: ^0.5.3
  cached_network_image: ^0.4.1+1
  fluro: ^1.3.1
  flutter:
    sdk: flutter
  flame: ^0.9.2
  cloud_firestore: ^0.7.3
  cloud_functions: ^0.0.1
  firebase_auth: ^0.5.12
  image_picker: ^0.4.5
  observable: ^0.22.1+3
  firebase_storage: ^1.0.0
  timeago: ^1.2.7
  firebase_messaging:
  firebase_database:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.6.0"
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/party-quest-icon.jpg" 
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # Got our emojis from: 
  # https://www.emojione.com/blog/emojione-to-release-version-40-with-special-preorder-offer

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Monterrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
    - family: LondrinaSolid
      fonts:
        - asset: fonts/LondrinaSolid-Regular.ttf
        - asset: fonts/LondrinaSolid-Thin.ttf
          weight: 100
        - asset: fonts/LondrinaSolid-Light.ttf
          weight: 200
        - asset: fonts/LondrinaSolid-Black.ttf
          weight: 800
    - family: Supercell
      fonts:
        - asset: fonts/Supercell-magic-webfont.ttf
          weight: 700
    - family: Baloo
      fonts:
        - asset: fonts/BalooTammudu-Regular.ttf
          weight: 700
        #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
